### PR TITLE
feat: LetsEncrypt support

### PR DESCRIPTION
**Pull request by michielbdejong**
Testing this live on interfaucet.michielbdejong.com now.

### CODE REVIEW

**Comment by emschwartz** [comment]
I'm seeing:
```
[500] Developer Error: app.use('/', le.middleware()) or le.middleware(app)
```

**Comment by michielbdejong** [comment]
Right, that's on http://. It's supposed to redirect, will find out what's going wrong there.

**Comment by michielbdejong** [comment]
@emschwartz redirect issue fixed now! Since then, I also added the flow used by e.g. https://github.com/interledgerjs/ilp-plugin-xrp-asym-client/pull/6/files#diff-04c6e90faac2675aa89e2176d2eec7d8R79

**Comment by michielbdejong** [comment]
@emschwartz bump

**Review by emschwartz — APPROVED** [review]

**Comment by michielbdejong** [comment]
Thanks!

**Pull request merged**
